on: [push, pull_request]

name: Continuous integration

jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          - beta
          # - nightly
    steps:
      - run: |
          apt update
          apt install -y libasound2-dev libudev-dev
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - run: cargo check
      - run: cargo fmt --all -- --check
      - run: cargo clippy -- -D warnings
      - run: cargo build
      - run: cargo test --features ci
  
  markdown:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actionshub/markdownlint@v3.1.4

  mdbook:
    name: MdBook
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          - beta
          # - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir bin
          curl -sSL $url | tar -xz --directory=bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - run: |
          cd docs
          mdbook build
